[package]
name = "asciidork-core"
version = "0.22.0"
edition = "2021"
description = "Asciidork core shared utils, types"
license = "MIT"

[dependencies]
lazy_static = "1.4.0"

[lints]
workspace = true

[lib]
doctest = false
