[package]
name = "asciidork-core"
version = "0.34.0"
edition = "2024"
description = "Asciidork core shared utils, types"
license = "MIT"

[dependencies]
lazy_static = "1.4.0"

[lints]
workspace = true

[lib]
doctest = false
